### ISSUE TITLE
Compiliation error after ImGUI submodule change

### ISSUE THREAD

**Issue by kwibjo** [Wando1423/Antario#26] opened 2017-05-15 08:16 UTC
`cmake .` no longer automatically removes all the ImGUI examples and font compressor from being compiled.

https://pastebin.com/2gM5ZrgW

**Comment by Wando1423** [comment] 2017-05-15 08:17
Fixed in this exact second. Try now. If it wont work, just redownload with --recursive.

**Comment by Wando1423** [comment] 2017-05-15 09:23
As you reacted with thumbs up, I think the problem is fixed, therefore I close the Issue and mark it as fixed.

**Closed by Wando1423** 2017-05-15 09:23 UTC
Labels: bug
